### ISSUE TITLE
Open event url in browser if service not recognized

### ISSUE THREAD

**Issue by srstanic** [leits/MeetingBar#194]
https://github.com/leits/MeetingBar/blob/a8065e7cdcfa51b201e8a1d7ef5c5a572300ceeb/MeetingBar/StatusBarItemControler.swift#L848

I'm curious why you decided to show a notification when the event URL is not recognized as one of the supported services instead of opening the event link in the browser? Opening the link in the browser is the default behavior of the `openMeetingURL()` function anyway. I find it limiting to not be able to click on the event and get the event URL opened in the browser. Would you consider changing this behavior or accepting a pull request?

**Comment by jgoldhammer** [comment]
Thanks for the bug report. 
At the moment we are searching through notes, location and url field of the appointment for known meeting services. If we do not find any, we will shows this message. Changing this would mean to detect all kinds of links and guessing to open one of them. We are accepting pull requests!

Alternatively you could add a custom regex under Advanced to let meetingbar handle your meeting service. Maybe you have an example link for us?

**Comment by srstanic** [comment]
I wouldn't call it a bug report, it's more of a UX improvement, if not even a preference. And I have to admit that my use case may be a bit out of the scope of the MeetingBar app, but here it is.

I schedule things to do in my calendar and sometimes these things have links. If they do, I put a link in the location field. Then when the time for this thing to do has come, I'd like to tap on the event in the MeetingBar to open the link. This is not strictly a meeting thing, more of a calendar thing. If I were designing this behavior, I would say that if a meeting service is not recognized, but there is at least one URL found in the event, pick the first one, and open it. Since you already check for links in the fields with the following order (location, url, notes), this would work perfectly for my use case and I believe it would be useful in case of unrecognized services as well. Certainly more useful than a notification about not recognizing a service.

Please let me know your thoughts! And thank you for a quick response!

**Comment by jgoldhammer** [comment]
The use case for this app is to visualize and join meetings with one click. I guess this feature request goes beyond it, but would indeed bring a benefit. I will try to implement a solution for this...

**Comment by jgoldhammer** [comment]
The link detection was part of another merge request which was merged. @leits removed this functionality for valid reasons (https://github.com/leits/MeetingBar/commit/efb157e5bb43ea0825e9d11ec9a0ac361f1bffe6#commitcomment-50292455). Maybe we can open this discussion again here to think about a useful integration. WDYT @srstanic about how this can be properly integrated?

**Comment by srstanic** [comment]
Going back to `openEvent(_:EKEvent)` I would suggest that the implementation of it does something like the following:
```
    if let meeting = getMeetingLink(event) {
        ...
        openMeetingURL(meeting.service, meeting.url, nil)
    } else if let eventUrl = getFirstUrl(event) {
       // open found URL in browser
    } else {
        sendNotification("status_bar_error_link_missed_title".loco(eventTitle), "status_bar_error_link_missed_message".loco())
    }

**Comment by leits** [comment]
Hi, @srstanic!

A few months ago, a new display of event notes appeared in the application. So you can now open the link explicitly, instead of implicit parsing through the App.
https://github.com/leits/MeetingBar/pull/263

We don't want to create unpredictable behavior for users, so we don't plan to add opening unrecognized meeting service links.

Also consider the functionality with custom regexes from the advanced section, where you have full control and accept all the risks. If you need it, you can add generic regex to any links and they will open for you.

**Comment by srstanic** [comment]
Alright, thanks for letting me know @leits !

**Comment by luckman212** [comment]
@srstanic I see this is closed now, but I have the exact same use case as you. I imagine many people would want this feature. When I stumbled onto this Issue I was really hoping a better decision would have been reached. It seems counterproductive to have all the info right there in the event, and yet pop up a no-op notification saying "not supported" when all we want is to open the URL with the default handler.

I understand not wanting to introduce complexity or unpredictability to the app, but I think a URL entered into the canonical `URL` field of the event warrants at least an option to simply open when the event is clicked.

@leits Sorry to comment on a closed issue, but the changes in #263 don't fully solve this, since only URLs from the `Notes` field are shown, strangely `URL` is ignored...

**Comment by luckman212** [comment]
@srstanic @leits what do you think about this PR #326 ?

**Comment by luckman212** [comment]
Adding @jgoldhammer -- any thoughts?

**Comment by srstanic** [comment]
@luckman212 Thanks for chiming in and creating a PR. The PR looks good to me, but in the end, it's up to the owner of the repo to make a decision.
