### ISSUE TITLE
Feature: Monitor clipboard for ad-hoc meeting links

### ISSUE THREAD

**Issue by roger-o3h** [leits/MeetingBar#197]
**Is your feature request related to a problem? Please describe.**
Sometimes folks paste me meeting links. The obvious solution is "uhhhh, click them?" But I like to use a specific browser for meetings, which MeetingBar does a smashing job with. For example, Google Meet tends to work best in Chrome, but Firefox is my daily browser.
If I could enable MeetingBar to monitor my clipboard as well as my calendars, it could open the proper browser for the particular meeting type when I copy the meeting link.

**Describe the solution you'd like**
Changes to the clipboard are detected.
When the clipboard contents match any of the meeting link regexes, MeetingBar launches the meeting link in my configured browser following its preferences.

**Describe alternatives you've considered**
I could just write an AppleScript to "Open contents of clipboard in Chrome," and bind it to a hotkey.

**Additional context**
Thanks for your work on this app, I use it every day and I recommend it to all my meeting-weary colleagues!

**Comment by jgoldhammer** [comment]
Hi @roger-o3h - I have a first version working, but I am not happy with the automatic behaviour to open the link directly after copying. Would it help to get a app notification and let the user decide to join the meeting by having an extra click? This way the functionality will not be that helpful because the user cannot prevent opening the meeting only when he wants to copy it. Another option would be a seperate shortcut to try opening the link in the clipboard...

 What do you think @leits and @roger-o3h ?

**Comment by leits** [comment]
What about menu item that appears if we recognize link in the clipboard? 
+ shortcut to open a link from the clipboard

Don't really want to monitor the clipboard for every change

**Comment by roger-o3h** [comment]
Hi! Either of the above solutions sounds great :) I agree the automatic behaviour might be more harmful than helpful. If I had to choose from the two.... maybe the notification with OK/Cancel? And I'm sure most users will want to turn off this feature selectively as well.

But as I say, I'm happy with any solution!

**Comment by jgoldhammer** [comment]
I have provided a pull request. Can you look at it @leits ?

**Comment by roger-o3h** [comment]
Awesome thank you @jgoldhammer! Excited to see if this makes it into a future build!
