### ISSUE TITLE
Bug: No app icon when no calendar selected

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#228]
_from email_

**Describe the bug**

if you don't select any calendars in MeetingBar and restart your computer, there's currently no icon (just blank space) for MeetingBar access.  

**Additional context**

Here's what happened to me: I hadn't used OSX calendar (just using google calendar on chrome). I went to set up my apple calendar per your nice instructions in-app, but for some reason, the apple calendar app could not find any linked calendars. So I restarted my computer which solved the apple calendar problem but now I can't open MeetingBar because it's already open. But no icon in the dock, and no apparent widget up in the top menu because I haven't synced any calendars with MeetingBar. I actually just got lucky and clicked around enough to find the blank space where I triggered the dropdown menu.  Hope that makes sense. Thanks again.

**Comment by jonorossi** [comment]
I had the same problem as I too hadn't used Calendar.app before MeetingBar.

I didn't restart macOS, but just closed MeetingBar's window because the refresh button wouldn't pick up the new calendars I synced from Google Calendar into Calendar.app. Tried killing the process and restarting, but couldn't get MeetingBar to re-display the set up wizard or anything.

I've ended up here and found where to click so I've got a calendar selected now. Thanks.
