### ISSUE TITLE
How do the regexes work? 

### ISSUE THREAD

**Issue by cdcharlebois** [leits/MeetingBar#259]
There's little help on here or in the UI about how I should use the regexes. Specifically, I'm looking to have the app recognize custom zoom links as in #164 . Is this possible using the regexes feature?

Thanks

**Comment by lilyball** [comment]
I agree that this really needs some documentation. For example, I originally would have expected the app to do normal URL detection on the meeting fields, and then to match regexes against those URLs. But from skimming the source it appears that it runs the regex on the whole field, and therefore the regex has to recognize the full URL in the context of the overall note. There's also no documentation for what regex engine (though it seems to be ICU), or what flags it uses (the answer seems to be "none", I wish it at least used `.anchorsMatchLines`). I guess the benefit of skipping data detectors for links is data detectors has bugs with links containing nested parentheses, though the app could get around that by just building a single regex to detect URLs correctly (I'm sure there's one floating around that properly matches conventions/RFCs) and then run the per-service/custom regexes against the results. This would definitely help with regexes as I then just need to match on the URL enough to classify it.

Another issue with the current approach is this means the regex has to properly match the full URL instead of just identifying it. This is a problem in that it requires regex authors to understand how to write a regex that matches a full URL. For example, I have a video app with a custom URL scheme, I'd like to write a regex that just matches `custom-video-scheme://` to identify it, but instead I have to figure out what regex is necessary to match the full URL. This is hard to do by hand as it requires figuring out issues like "if I find a period, does it belong to the URL, or is it a trailing period on a sentence that the URL is in?"

And there's more subtle issues too, like the fact that the regexes as currently written will match things like `not-https://meet.google.com/foo`, which is not in fact a meeting link but will be parsed as a google meet URL.

In any case, the best idea for how to write regexes right now is probably to look at the current built-in URLs:

https://github.com/leits/MeetingBar/blob/1cbe619369d4c9b9095de8183f9ec75cb750aee5/MeetingBar/Constants.swift#L21-L63

**Comment by lilyball** [comment]
Another issue I'm seeing with current regexes is a link like `https://gotzoom.com/join` will be parsed as a webex link. This is probably not a big deal but is still weird.

**Comment by cdcharlebois** [comment]
@lilyball thanks for your comment! Using the values in there as an example, I was able to work my way down to a regex that works for my company's custom Zoom domain & personal meeting invites (PMIs):
`https?:\/\/COMPANY.zoom.us\/my\/[0-9a-zA-Z?=.]*`
