### ISSUE TITLE
Feature: Send meetings via MQTT

### ISSUE THREAD

**Issue by jverhoeks** [leits/MeetingBar#281]
**Is your feature request related to a problem? Please describe.**
I use home-assistant to automate my home and notify my family members. Having a notification when i'm in a meeting prevents accidental walk-ins.

**Describe the solution you'd like**
Have a configurable MQTT target to publish messages when a meeting starts (name, time, duration) and one when the meeting stops.  Preferable with MQTT 3 and 5 support and user/password + certificates as authentication.

**Describe alternatives you've considered**
I worked on a python script to scrape google calendar, but meetingbar has all the integration already and a very stable interface.

**Additional context**
I'm working an a next version of this https://github.com/edrans/on-air/tree/main/on-air-display with the meeting name and duration.  The meeting name and duration is something i'm looking for.

**Comment by leits** [comment]
Thanks for the request, @jverhoeks!

MeetingBar doesn't send data anywhere on the outside itself, it's by design.

But soon there will be an Advanced feature with a trigger at the beginning and end of the meeting of the custom AppleScript.
You can follow it here: #148. I think it's the best place to make your integration.
