### ISSUE TITLE
Feature: Jitsi Meet app support

### ISSUE THREAD

**Issue by guyguy333** [leits/MeetingBar#291]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when Firefox is opening to start a Jitsi Meet whereas I've desktop app.

**Describe the solution you'd like**

I would like MeetingBar to open Jitsi meetings in Jitsi Meet app when available : https://github.com/jitsi/jitsi-meet-electron. It would be a feature similar to Zoom or Teams. 

**Describe alternatives you've considered**

I've to copy/paste the link in Jitsi Meet app manually.

**Additional context**

App can be opened using `jitsi-meet://https://meet-host/room-name` (example: `jitsi-meet://https://meet.jit.si/meeting-bar`)

**Comment by jgoldhammer** [comment]
I have implemented it now and will push it soon.

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/3872101/130335347-6d2ed7e7-112b-4d07-8f45-abc91eeefb89.png">

The correct link is: jitsi-meet://meet.jit.si/meeting-bar instead of jitsi-meet://https://meet.jit.si/meeting-bar

**Comment by guyguy333** [comment]
Great 👍 Thanks !!
