### ISSUE TITLE
Feature: Get multiple notifications 5 min / 1 min and when meeting starts

### ISSUE THREAD

**Issue by koenvb** [leits/MeetingBar#305]
**Is your feature request related to a problem? Please describe.**
As a user I want to get multiple events so I do not forget the meeting

**Describe the solution you'd like**
Make it possible to set multiple events

**Comment by mattogodoy** [comment]
I came here looking for the same. The Apple Calendar app gives you an option to "snooze" the meeting.
Here's a screenshot:
![telegram-cloud-photo-size-4-5846047598140568769-x](https://user-images.githubusercontent.com/1627178/130411602-076b77a6-40c7-4766-8268-c4a93fdcb371.jpg)

I find it very useful, especially the "snooze until" options. In this screenshot you can only see the last one because that meeting was happening right then, but it also has options to snooze until 5 minutes before, 2 minutes before, etc.

**Comment by jgoldhammer** [comment]
This is implemented and will be released in the next version.
