### ISSUE TITLE
Bug: In multiscreen, screen without focus doesn't display meeting text

### ISSUE THREAD

**Issue by ltaupiac** [leits/MeetingBar#354]
**App version**
3.8

**Describe the bug**
With 2 screens connected (iMac M1), when the focus is set on one screen, the focused screen display next meeting text while unfocused screen display blank space

**To Reproduce**
1. Have meeting text display on the main screen
2. Click on the main screen (desktop or any applications)
3. See that MeetingBar display meeting text on the main screen
4. See error on the second screen when MeetingBar is displaying blank space
5. Set focus on the second screen, meeting text appear while it disappears on the main screen

**Expected behavior**
Display next meeting text on all screens

**Screenshots**
Main screen with focus
<img width="887" alt="image" src="https://user-images.githubusercontent.com/108308/135061878-d0e97045-4ef7-461f-96bd-196e8bb7c823.png">
Second screen without focus
![image](https://user-images.githubusercontent.com/108308/135062212-540665bf-7012-4234-bb84-d6153b48267b.png)

**Desktop (please complete the following information):**
 - macOS version: 11.6 Imac 24" M1

**Comment by david-dasilva** [comment]
Thanks, I was wondering what was happening with my menu bar in the not focused screen!
I realised it was only a MeetingBar issue because I can still read the clock and the rest of the menu bar text (File, Edit...) but only the text from MeetingBar is invisible.
<img width="840" alt="Capture d’écran 2021-12-30 à 09 45 11" src="https://user-images.githubusercontent.com/372391/147735871-8b6a3553-caf7-42da-b5fa-9b0450d89a3e.png">

**Comment by david-dasilva** [comment]
Small change in v3.10.1 : now the text is shown, but not in the same color as the rest of the menubar.
For example : text is grey on dark background while other text are white, or light grey on light background while other text are black.
![Capture d’écran 2022-02-04 à 10 50 36](https://user-images.githubusercontent.com/372391/152508605-542664f8-dfbb-4be9-84da-07434579001d.png)
<img width="1675" alt="Capture d’écran 2022-02-04 à 10 52 25" src="https://user-images.githubusercontent.com/372391/152508625-6cd93992-3c80-4053-bd4e-266bc9414727.png">

**Comment by xeroxoid** [comment]
Same issue here. The text is visible but light grey thus not readable.

**Comment by jgoldhammer** [comment]
I have prepared a fix for that. It looks like that:

![image](https://user-images.githubusercontent.com/3872101/161444038-15328661-9ea4-4e5f-9f50-9a445186ed09.png)

WDYT @xeroxoid , @rvadaga , @david-dasilva and @ltaupiac ?

**Comment by xeroxoid** [comment]
Much better compared to now 😅

<img width="439" alt="Screenshot 2022-04-06 at 09 26 56" src="https://user-images.githubusercontent.com/1199451/161909429-bfc620ba-bde5-459a-8333-43a6731c0aa8.png">

**Comment by xeroxoid** [comment]
Way better compared to now 😅

<img width="310" alt="Screenshot 2022-04-06 at 09 28 55" src="https://user-images.githubusercontent.com/1199451/161909646-a4c2cf6a-9964-4f08-9787-11803c3a587d.png">

**Comment by david-dasilva** [comment]
I confirm, the fix works in beta 4.0 🚀 Thanks!

**Comment by tizmagik** [comment]
Yes, thank you for fixing! 🙏

**Comment by david-dasilva** [comment]
Wait, I'm afraid it's good only for dark backgrounds. 😢 
Active screen with light background :
![Active screen, light background](https://user-images.githubusercontent.com/372391/165464486-5442d290-e807-4ec9-bb9e-2da5cce4999e.png)

Inactive screen with light background :
<img width="1151" alt="Capture d’écran 2022-04-27 à 09 23 38" src="https://user-images.githubusercontent.com/372391/165464599-da61a81e-720f-4816-a8a7-33308b5a8711.png">

**Comment by david-dasilva** [comment]
I'm not an Swift dev in any way, but I think that using the key `UIViewControllerBasedStatusBarAppearance` with the value true inside `/MeetingBar/info.plist` could do the trick (and remove any code overriding the text color I guess).
[Here is the doc about the property](https://developer.apple.com/documentation/bundleresources/information_property_list/uiviewcontrollerbasedstatusbarappearance)
Sorry I can't create a PR for this because I don't know how to test it locally first 🤷
