### ISSUE TITLE
Feature: Enable links in HTML code

### ISSUE THREAD

**Issue by hbarthels** [leits/MeetingBar#371]
**The Problem**
In the meeting details submenu, links that are in HTML code (example `<a href="https://www.example.com/">link</a>`) are not clickable. In my case, those links usually point to a shared meeting notes document, so it would be convenient to be able to quickly access them during a meeting.

**Idea for Solution**
Make those links clickable.

**Alternative Solution**
Related to #370, I was thinking that perhaps it could also be useful to extract all the links that are **not** related to joining a meeting and put them into a separate section of the submenu. This could be useful for Zoom meetings, where the notes frequently contain a lengthy description of all the different ways in which the meeting can be joined: If it was possible to customize the meeting details submenu, this way it would be possible to save a lot of space without loosing access to the useful links.
However, I'm not sure if a lot of other people would find this useful, so I'm not sure if it's worth the effort.

**Comment by hbarthels** [comment]
A variation on the "alternative solution" that is perhaps a bit more general: One could make it possible to only show a summary of the notes that only contains what is matched by a regular expressions provided by the user. In my case for example, I would write a regular expression that detects the links to meeting notes. Of course, for me this would only be useful if those links are clickable.

**Comment by jsmayo** [comment]
Going along with @hbarthels, many of my meetings also include document links within the details (GDocs, GSheet, etc). However, MeetingBar is parsing those URLs as meeting links, which results in an error message whenever the user either clicks a URL or copies a URL from within the details section. Just in case the click target was being sent to the browser, I tried setting 'Open all meeting links in' to 'Default Browser', but experienced the same behavior as before. 

As a side note, there was a bit of difficulty when trying to copy info within the details section because the submenu kept auto dismissing itself.

**Comment by leits** [comment]
It should work now. Try to double-click on the highlighted link to follow it!
