### ISSUE TITLE
Feature: cli access

### ISSUE THREAD

**Issue by cagdassalur** [leits/MeetingBar#394]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I would like to have access to the strings generated for the status bar from command line. Maybe to run a command to see my upcoming meetings, minutes left until next meeting and minutes until the current meeting ends, maybe even to join

**Describe alternatives you've considered**
using ical-buddy and generating a human readable string from that, but I maintain a lot of settings and functionality through MeetingBar so it would be great to be able to use it.

**Additional context**
Does this exist somehow? I wasn't able to find it..

**Comment by leits** [comment]
Hi @cagdassalur!
Since the 4.4 version MeetingBar has integrated with the macOS Shortcuts app.
You can configure desired actions inside the shortcut and run it from a terminal.

For example, this is the shortcut configured to get the nearest meeting title from MeetingBar:
<img width="1312" alt="image" src="https://github.com/leits/MeetingBar/assets/12017826/c63b5a33-e9a8-49e9-86cf-cb000485924c">

You can run it in a terminal like this:
``` 
$ shortcuts run "Get Next Event Details"
```
I don't know why but the output is not going directly to stdout but you can pass it through the pipe further:
```
 $ shortcuts run "Get Next Event Details" | cat
Team sync (week2)%                                                                                                       


```

I think this should be enough for automation. Building a CLI requires a separate package and it seems overkill now.

Is such a solution suitable for you?

**Comment by cagdassalur** [comment]
Oh, even better! I was already thinking to integrate it to https://github.com/FelixKratz/SketchyBar, so having these actions will be great to put into a menu bar like how it is in the original :), thanks!

**Comment by leits** [comment]
Awesome!

**Comment by sameer1612** [comment]
> Oh, even better! I was already thinking to integrate it to https://github.com/FelixKratz/SketchyBar, so having these actions will be great to put into a menu bar like how it is in the original :), thanks!
> 
> <blockquote><img src="https://opengraph.githubassets.com/24dcf1358b3baea97be037cfda9e8a24fadeb294998f26fb430579e878188187/FelixKratz/SketchyBar" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/FelixKratz/SketchyBar">GitHub - FelixKratz/SketchyBar: A highly customizable macOS status bar replacement</a></strong></div><div>A highly customizable macOS status bar replacement - GitHub - FelixKratz/SketchyBar: A highly customizable macOS status bar replacement</div></blockquote>

Did you add it to sketchybar? I am also gonna attempt the same. Will save lot of headache if already done.

**Comment by waynehoover** [comment]
@sameer1612 I created a [bash script](https://gist.github.com/waynehoover/6d287fff306870392f07f7bf55113c06) to get the relative time in sketchybar using this shortcut, then used that in sketchybar.

@leits It would be great if the shortcut had the ability to return the relative time (like "in 2h") instead of just the start date.
