### ISSUE TITLE
"HTTP" meeting

### ISSUE THREAD

**Issue by Nainterceptor** [leits/MeetingBar#45]
Hello,

At work, we choose to use opensources products when it fit our needs, so we don't use Google meetings nor Zoom, but Jitsi, on a self-hosted instance.

I think it's a good option to be able to open meeting in default web browser when it's not a google meeting or zoom meeting ?
And maybe, meeting creation will just open calendar creation event ?

Have a nice day, and thanks for the product,
Gaël

**Comment by fuzzy76** [comment]
I believe Jitsi was fixed here: https://github.com/leits/MeetingBar/commit/a255d77c0a8b973febfe00799e76e8da0b77d3ec

**Comment by Itaybre** [comment]
@Nainterceptor can you post an example URL? (you can replace your website/IP so there is no security threat for your company)

@fuzzy76 It is unlikely that it was fixed by that commit, because they are probably using an IP address or a non public domain, probably a more generic regex will be required or just an option for the user to insert their custom domain

**Comment by Nainterceptor** [comment]
@Itaybre Hello, `https://domain-of-our-jitsi-server.tld/some-room-name`

**Comment by leits** [comment]
Custom regexes added in https://github.com/leits/MeetingBar/releases/tag/v2.0
@Nainterceptor @Phill93 check it out!
