### ISSUE TITLE
Bug: Create meeting with different user

### ISSUE THREAD

**Issue by MohamadKh75** [leits/MeetingBar#520]
**App version**
4.0.6

**Installation source**

- homebrew

**Describe the bug**
I use the `Create meeting` button to create a meeting but It doesn't use `?authuser=x` to properly handle it.
I have user X on my chrome but using user Y in meetingBar so I need to create meetings with my user Y.
BTW, Joining meetings is ok (since it uses `?authuser=x` in the link)

**To Reproduce**

1. Open meetingBar menu
2. Click on "Create meeting"
3. See the meeting is created with another user

**Expected behavior**
To create the meeting with logged in user (in meetingBar)

**Screenshots**
None

**Desktop (please complete the following information):**

- macOS version: Monterey - 12.6

**Additional context**
None

**Comment by MohamadKh75** [comment]
Exists in `4.1.0` too

**Comment by leits** [comment]
Hi @MohamadKh75,
Thanks for the report. But this behavior is by design, the app doesn't know what account you want to use.
But you can use a custom create meeting URL to specify the user:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/12017826/196038947-3e14d8ae-c560-4923-858f-b0b263e815f0.png">
