### ISSUE TITLE
Bug: MeetingBar not showing on all screens/monitors

### ISSUE THREAD

**Issue by lookasu** [leits/MeetingBar#534]
**4.2.1**

**Installation source**
- AppStore

**App Version**
- 4.2.1

**Calendars provider (selected in app)**
- Direct Google Calendar API integration

**Describe the bug**
When multiple screens/monitors connected MeetingBar only appears on one of them. Other apps appear on all.

**To Reproduce**
1. Connect multiple screens/monitors

**Expected behavior**
MeetingBar appearing on all screens

**Desktop (please complete the following information):**
 - macOS version: 12.5

**Additional context**
Not sure if this is a bug or a feature request, please feel free to change.

**Comment by jgoldhammer** [comment]
Hi @lookasu  - I do not understand what exactly your request is. Do you think, Meetingbar should open the menubar on both displays? Currently meetingbar is shown in the menubar of all screens - maybe your mac builtin display has not enough space to show it?

**Comment by beltrachi** [comment]
Hi,
I could reproduce this with a long event title. I'm using 2 screens. On the small screen it disappeared, probably because it did not fit. If you go to MeetingBar settings and reduce the event length or change it to "." it appears everywhere in my case.

In other cases, it depends on how long is the current application open. Some apps have a lot of menu options and then the app widget gets hidden.

Not sure if there is a way to improve that experience. Would be great if the event title gets reduced when it does not fit in the window, but its just an idea.

**Comment by timodonoghue** [comment]
I had this same issue and wondered why MeetingBar was only showing on my extended display rather than my main display.  My extended display is 4k and has more horizontal real estate.  Removing some existing icons and/or shortening the event title (in MeetingBar config) resolves the issue and it reappears on (smaller) main display.

Perhaps consider a feature request to "over shorten" meeting title so at least MeetingBar renders something rather than nothing?  (i.e. echo @beltrachi's suggestion)

The combination of current behavior combined with https://github.com/leits/MeetingBar/issues/627 (which means it is nearly impossible to see MeetingBar on a display which doesn't have focus) could certainly be improved.

Not a bug IMO; functions as expected (if not ideally).

**Comment by leits** [comment]
Hi folks,

Yes, it's not a bug, but a macOS behavior. 

I'll leave one issue opened for the conversation there > #613
