### ISSUE TITLE
Feature: remove alert dismissal of events

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#564]
### Issue that this suggestion fixes

When you dismiss the current meeting, a pop-up appears.  It's (a) pointless and (b) annoying. 

Why is it "pointless"?

* But you can't do anything with this, it only has an "Ok" button.
* You know the current meeting has been dismissed, because it no longer appear in the toolbar. 

Why is it "annoying"?

* You're forced to do something that does nothing and take time.

### Solution description

Either:

(a) Show a toaster notification.
(b) Do nothing (recommended) .

### Alternatives considered

None

**Comment by untitled500** [comment]
I think a toast is useful for the first few instances (maybe 5?) when this happens - so that new users know that something has happened.

As an alternative to Do nothing, we could just temporarily show "Dismissed" for 2 seconds in the menu bar before reverting back to showing meetings.

**Comment by leits** [comment]
Hi @alexec,
Thanks for the ticket.

Usually, it's just a toaster about the result of the action. But because your notification for the app is disabled you get the alert instead.

It looks like we need to reconsider cases when we want to show alerts when the user disabled notifications. But in general, this functionality works as expected to notify a user about the result of the action.

**Comment by clstokes** [comment]
I would appreciate if a preference could be added to disable these. I also find them annoying and unhelpful.
