### ISSUE TITLE
Feature: Monochrome/white (menu bar) icon

### ISSUE THREAD

**Issue by pro-sumer** [leits/MeetingBar#612]
### Issue that this suggestion fixes

The purple Teams icon in my menu bar is drawing too much attention (compared to all the monochrome/white icons around it)

### Solution description

Please offer monochrome/white icons next to the existing coloured icons.

### Alternatives considered

Paying (the subscription) for Flexibits Premium to use Fantastical (instead of MeetingBar).

**Comment by leits** [comment]
Thanks for the request, @pro-sumer!

Considering the volume of the current settings and the possibility of not displaying the event icon in general, I do not think that it is advisable to inflate the application with monochrome versions of the icon for each service.

And since no one else has followed this ticket, I will close it, sorry!
