### ISSUE TITLE
💬 Request new service integration

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#62]
If you use a service that isn't supported in MeetingBar, leave a comment here with the service's name and an example link to the meeting. Thank you!

--------
Currently supported services:
- Google Meet
- Zoom
- Google Hangouts
- Microsoft Teams
- Amazon Chime
- Cisco Webex
- Jitsi
- Ring Central
- GoToMeeting
- GoToWebinar
- BlueJeans
- 8x8
- Demio
- Join.me
- ZoomGov
- Whereby
- Uber Conference
- Blizz
- VSee
- StarLeaf
- Google Duo
- Tencent VooV
- Skype
- Skype For Bussines
- Lifesize
- Facebook Workspace

**Comment by ZNielsen** [comment]
Chime integration would be great! Links to meetings come in the form of `https://chime.aws/<meeting_id>`, for example https://chime.aws/1234567890

**Comment by leits** [comment]
Thanks, @ZNielsen.
There is support for the service, I just forgot to add it here.
But I see that parsing may not be correct. I relied on `app.chime.aws`.
I will fix this in the next release!

**Comment by ZNielsen** [comment]
Awesome, thanks!

**Comment by paul8620** [comment]
How can I create my meetings by default in ringcentral

**Comment by scorgn** [comment]
Is there any way we could implement custom regex expressions? I think it would be a great way to support any type of meeting that might not otherwise be supported.

Another suggestion that would fix @paul8620's issue would be to let people implement a custom url for the "Create Meetings" functionality.

My specific scenario is that my email provider (Outlook) will provide "Safe Links" for the meetings which doesn't match the regex that MeetingBar is looking for. In the meantime I will try to add the regex into the source and build it myself, but it would be a good feature to have in general.

If this is something you guys would want to go forward to I could take a stab at implementing it. I have been wanting to dip my feet in Swift.

**Comment by AndreasBackx** [comment]
Would love to get support for Facebook Workplace, the format is as follows: `https://SUBDOMAIN.workplace.com/meet/MEETING_ID/`.

**Comment by jgoldhammer** [comment]
@paul8620 - we will implement that in https://github.com/leits/MeetingBar/issues/105

**Comment by jgoldhammer** [comment]
@ZNielsen : the links for aws chime should be handled correctly now. Can you confirm?

**Comment by ZNielsen** [comment]
Confirmed, join next event meeting works with amazon chime.

**Comment by leits** [comment]
Propose new services in [Discussion](https://github.com/leits/MeetingBar/discussions/108)!
