### ISSUE TITLE
Notification for updates

### ISSUE THREAD

**Issue by Itaybre** [leits/MeetingBar#83]
**Is your feature request related to a problem? Please describe.**
As an user, I would like to always have the latest version of MeetingBar available.

**Describe the solution you'd like**
On each (or after x time) do a request to check if there is a newer version available. 
If so, provide an auto update

**Comment by jgoldhammer** [comment]
It is worth to have this? We could use Sparkle and provide the updates via github, but there are tools like homebrew which automatically update your tools. (maybe not everybody is using it?). What do you think @leits?

Sparkle 2.0 (currently beta) can also update sandboxed apps. (see https://github.com/sparkle-project/Sparkle/tree/2.x)

**Comment by leits** [comment]
This was very relevant when the application could only be installed manually.

Now the average user installs it through AppStore. A user with deeper technical knowledge can use homebrew.
Both have internal mechanisms for updating the program.
Manual installation remains as part of homebrew integration (requires dmg public link).

We work very carefully with user data.
Therefore, I do not think that adding external requests from the application is worth it.

And that's why I close this feature request, as it is no longer relevant.

**Comment by leocaseiro** [comment]
How about a link to check for updates? I was using homebrew until yesterday, and I noticed that I was still using the app v1.xx

When I noticed that we had 3.x version I was surprised with the latest version which is way better! Not sure why homebrew was not updating...
